### ISSUE TITLE
Syntax error on python when build from source

### ISSUE THREAD

**Issue by KuribohG** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#542]
I followed the instructions in README, and got the following compile error:
```
[  2%] Built target murmurhash
[  4%] Built target cpprpr
[  6%] Built target _rprUsd_pythonfiles
[  6%] Built target schema_dir
[  7%] Built target rprUsdSchema
[ 25%] Built target rprUsd_headerfiles
[ 50%] Built target rprUsd
[ 58%] Built target _rprUsd
[ 58%] Built target python
[ 76%] Built target hdRpr_headerfiles
[ 77%] Generating files
Traceback (most recent call last):
  File "/home/taichigraphics/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/python/generateFiles.py", line 15, in <module>
    import generateGeometrySettingFiles
  File "/home/taichigraphics/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/python/generateGeometrySettingFiles.py", line 15, in <module>
    from houdiniDsGenerator import generate_houdini_ds
  File "/home/taichigraphics/RadeonProRenderUSD/pxr/imaging/plugin/hdRpr/python/houdiniDsGenerator.py", line 64
    encoded_name = hou.encode(f'rpr:{condition_name}')
                                                    ^
SyntaxError: invalid syntax
make[2]: *** [pxr/imaging/plugin/hdRpr/CMakeFiles/hdRpr.dir/build.make:66: pxr/imaging/plugin/hdRpr/config.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:665: pxr/imaging/plugin/hdRpr/CMakeFiles/hdRpr.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I'm using python 3.8.10, and my OS is Ubuntu 20.04. How should I fix this?

**Comment by KuribohG** [comment]
This magically solved after I reinstall my Linux...
